name: 'Publish'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'utv'
        type: choice
        options:
        - utv
        - test
        - prod
jobs:
  print-utv:
    name: print-utv-job
    runs-on: ubuntu-latest
    steps:
      - name: shipit
        run: echo running code
